services:
  - type: web
    name: mediacloudsubtrans  # Cambia esto por tu nombre de servicio
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7656468639:AAFZLaXapxnejcnsWnMlfK_m4zPQSvCvUK  # Obtén de @BotFather
      - key: RENDER
        value: true
      - key: RENDER_SERVICE_NAME
        value: mediacloudsubtrans  # Debe coincidir con 'name' arriba
