services:
  - type: web
    name: subtitle-translator-bot
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip cache purge
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7656468639:AAFZLaXapxnejcnsWnMlfK_m4zPQSvCvUKo
      - key: WEBHOOK_URL
        value: https://mediacloudsubtrans.onrender.com
