services:
  - type: web
    name: mediacloudsubtrans
    runtime: python
    pythonVersion: "3.9"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7656468639:AAFZLaXapxnejcnsWnMlfK_m4zPQSvCvUKo
      - key: WEBHOOK_URL
        value: https://mediacloudsubtrans.onrender.com
      - key: RENDER
        value: "true"
