services:
  - type: web
    name: subtitle-translator-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_bot_token
      - key: WEBHOOK_URL
        value: https://your-service-name.onrender.com
